// Generated by https://quicktype.io

export interface LoginResponse {
    message: string;
    accessToken: AccessToken;
    user: User;
}

export interface AccessToken {
    token: string;
    expiresAt: string;
}

export interface User {
    id: string;
    username: string;
    email: string;
    role: string;
    createdAt: string;
    updatedAt: string;
}

// Generated by https://quicktype.io

export interface RefreshResponse {
    message: string;
    accessToken: AccessToken;
    user: User;
}

// Generated by https://quicktype.io

export interface RegisterResponse {
    message: string;
}

// Generated by https://quicktype.io

export interface LogoutResponse {
    message: string;
}

// Generated by https://quicktype.io

export interface VerifyResponse {
    message: string;
}

// Generated by https://quicktype.io

export interface ResendVerifyResponse {
    message: string;
}

// Generated by https://quicktype.io

export interface PasswordChangeResponse {
    message: string;
}

// Generated by https://quicktype.io

export interface SendPasswordResetResponse {
    message: string;
}

// Generated by https://quicktype.io

export interface PasswordResetResponse {
    message: string;
}
